version: "3.6"
services:
  pgsql:
    image: postgres
    volumes:
      - ~/neuroarqdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 5s
      timeout: 2s
      retries: 10
  api:
    build: .
    environment:
      - DB_HOST=pgsql
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - ALLOWED_HOSTS=0.0.0.0, localhost
      - CORS_ALLOWED_ORIGINS=http://localhost:3000

    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "5678:5678"
      - "5677:5677"
    command:
      - /bin/bash
      - -c
      - |
        pip install debugpy
        python manage.py migrate
        python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    depends_on:
      pgsql:
        condition: service_healthy
networks:
  default:
    external: true
    name: neuroarq
